name: Reapply My Custom Changes After Sync
# I'm removing the trigger for this... it's not relevant to my current setup, i don't think.

on:
    workflow_dispatch:

jobs:
  reapply-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all branches and history
        ref: main

    - name: Set up Git
      run: |
        git config --global user.email "orcnog@gmail.com"
        git config --global user.name "orcnog"

    - name: Fetch all branches and checkout 'orcnog'
      run: |
        git fetch origin  # Fetches all branches
        git checkout orcnog

    - name: Attempt to rebase custom changes
      run: git rebase main

    - name: Push changes back to custom branch (if rebase was successful)
      if: success()
      run: git push origin orcnog --force-with-lease
